apiVersion: apps/v1
kind: Deployment
metadata:
  name: zxtim-deployment
spec:
  selector:
    matchLabels:
      app: zxtim
  replicas: 1
  template:
    metadata:
      labels:
        app: zxtim
    spec:
      containers:
        - name: zxtim
          image: zxtim:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http     #端口号名称
              containerPort: 8080
              hostPort: 8080
              protocol: TCP
            - name: websocket
              containerPort: 8089
              hostPort: 8089
              protocol: TCP
            - name: rpc
              containerPort: 9001
              hostPort: 9001
              protocol: TCP
