apiVersion: v1
kind: Service
metadata:
  name: zxtim-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  selector:
    app: zxtim
  type: NodePort
